from pathlib import Path

# Store: add a family-wide durable topology read without changing the existing
# session-local LoadedSession.agents contract.
p = Path("crates/ion-core/src/store/mod.rs")
text = p.read_text()
old = '''    Load {\n        session_id: SessionId,\n        reply: oneshot::Sender<Result<LoadedSession, StoreError>>,\n    },\n    LatestSession {\n'''
new = '''    Load {\n        session_id: SessionId,\n        reply: oneshot::Sender<Result<LoadedSession, StoreError>>,\n    },\n    LoadAgentFamily {\n        family_session_id: SessionId,\n        reply: oneshot::Sender<Result<Vec<AgentRecord>, StoreError>>,\n    },\n    LatestSession {\n'''
if old not in text:
    raise SystemExit("StoreCommand Load anchor missing")
text = text.replace(old, new, 1)
old = '''    pub async fn load(&self, session_id: SessionId) -> Result<LoadedSession, StoreError> {\n        self.request(|reply| StoreCommand::Load { session_id, reply })\n            .await\n    }\n\n    /// Token usage rows recorded for one session (DESIGN.md §27.2).\n'''
new = '''    pub async fn load(&self, session_id: SessionId) -> Result<LoadedSession, StoreError> {\n        self.request(|reply| StoreCommand::Load { session_id, reply })\n            .await\n    }\n\n    /// Load the complete durable semantic agent family while preserving\n    /// `LoadedSession::agents` as a session-local view. Every returned record\n    /// is validated by loading the session it addresses.\n    pub(crate) async fn load_agent_family(\n        &self,\n        family_session_id: SessionId,\n    ) -> Result<Vec<AgentRecord>, StoreError> {\n        self.request(|reply| StoreCommand::LoadAgentFamily {\n            family_session_id,\n            reply,\n        })\n        .await\n    }\n\n    /// Token usage rows recorded for one session (DESIGN.md §27.2).\n'''
if old not in text:
    raise SystemExit("SessionStore load anchor missing")
p.write_text(text.replace(old, new, 1))

p = Path("crates/ion-core/src/store/sql.rs")
text = p.read_text()
old = '''        StoreCommand::Load { session_id, reply } => {\n            let _ = reply.send(load(connection, session_id));\n        }\n        StoreCommand::Usage { session_id, reply } => {\n'''
new = '''        StoreCommand::Load { session_id, reply } => {\n            let _ = reply.send(load(connection, session_id));\n        }\n        StoreCommand::LoadAgentFamily {\n            family_session_id,\n            reply,\n        } => {\n            let _ = reply.send(load_agent_family(connection, family_session_id));\n        }\n        StoreCommand::Usage { session_id, reply } => {\n'''
if old not in text:
    raise SystemExit("sql Load command anchor missing")
text = text.replace(old, new, 1)
anchor = '''fn load_agents(\n    connection: &Connection,\n    session_id: SessionId,\n'''
if anchor not in text:
    raise SystemExit("load_agents anchor missing")
family_fn = '''fn load_agent_family(\n    connection: &Connection,\n    family_session_id: SessionId,\n) -> Result<Vec<AgentRecord>, StoreError> {\n    let mut statement = connection.prepare(\n        "SELECT DISTINCT session_id FROM agents\n         WHERE family_session_id = ?1 ORDER BY session_id",\n    )?;\n    let mut rows = statement.query([family_session_id.as_uuid().to_string()])?;\n    let mut session_ids = Vec::new();\n    while let Some(row) = rows.next()? {\n        let raw: String = row.get(0)?;\n        let session_id = SessionId::parse(&raw).ok_or_else(|| {\n            StoreError::Sqlite("agent family has a corrupt target session id".to_owned())\n        })?;\n        session_ids.push(session_id);\n    }\n    drop(rows);\n    drop(statement);\n\n    let mut agents = Vec::new();\n    for session_id in session_ids {\n        let loaded = load(connection, session_id)?;\n        agents.extend(\n            loaded\n                .agents\n                .into_iter()\n                .filter(|agent| agent.family_session_id == family_session_id),\n        );\n    }\n    let root = AgentId::root(family_session_id);\n    if !agents.iter().any(|agent| {\n        agent.id == root\n            && agent.session_id == family_session_id\n            && matches!(agent.history, AgentHistory::Root)\n    }) {\n        return Err(StoreError::Sqlite(format!(\n            "agent family {family_session_id} has no durable root"\n        )));\n    }\n    Ok(agents)\n}\n\n'''
text = text.replace(anchor, family_fn + anchor, 1)
p.write_text(text)

# Family: expose one durable topology lookup. This does not move runtime
# residency into Family yet; it only makes Family authoritative for whether a
# handle is shared-history or separately hosted.
p = Path("crates/ion-core/src/agent.rs")
text = p.read_text()
text = text.replace(
    '''use crate::store::{AgentRecord, LoadedSession, SessionStore, StoreError};\n''',
    '''use crate::store::{AgentHistory, AgentRecord, LoadedSession, SessionStore, StoreError};\n''',
    1,
)
anchor = '''#[derive(Debug, Clone)]\nstruct RetainedAgent {\n    lane_name: String,\n}\n'''
replacement = '''#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub(crate) enum AgentTarget {\n    SharedHistory { session_id: SessionId },\n    SeparateSession { session_id: SessionId },\n}\n\n#[derive(Debug, Clone)]\nstruct RetainedAgent {\n    lane_name: String,\n}\n'''
if anchor not in text:
    raise SystemExit("RetainedAgent anchor missing")
text = text.replace(anchor, replacement, 1)
anchor = '''    #[must_use]\n    pub const fn root(&self) -> AgentId {\n        self.root\n    }\n\n    /// Admit a retained shared-history agent from the control parent's current\n'''
replacement = '''    #[must_use]\n    pub const fn root(&self) -> AgentId {\n        self.root\n    }\n\n    /// Resolve one durable family address to its history/runtime topology.\n    /// This lookup is store-backed so separately hosted descendants admitted\n    /// after `Family::attach` are still recognized without process-local\n    /// registration.\n    pub(crate) async fn target(&self, agent_id: AgentId) -> Result<AgentTarget, Error> {\n        let agents = self.store.load_agent_family(self.session_id).await?;\n        let agent = agents\n            .iter()\n            .find(|agent| agent.id == agent_id)\n            .ok_or(Error::UnknownAgent(agent_id))?;\n        match &agent.history {\n            AgentHistory::Root | AgentHistory::SharedLane { .. }\n                if agent.session_id == self.session_id =>\n            {\n                Ok(AgentTarget::SharedHistory {\n                    session_id: agent.session_id,\n                })\n            }\n            AgentHistory::Fresh | AgentHistory::Fork { .. }\n                if agent.session_id != self.session_id =>\n            {\n                Ok(AgentTarget::SeparateSession {\n                    session_id: agent.session_id,\n                })\n            }\n            _ => Err(Error::Inconsistent(agent_id)),\n        }\n    }\n\n    /// Admit a retained shared-history agent from the control parent's current\n'''
if anchor not in text:
    raise SystemExit("Family root anchor missing")
text = text.replace(anchor, replacement, 1)
p.write_text(text)

# Unified host: route by Family's durable topology instead of using
# UnknownAgent as a backend-discovery mechanism.
p = Path("crates/ion-core/src/delegate.rs")
text = p.read_text()
old = '''                HostAgentToolKind::Start => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    let objective = match host_string_arg(&arguments, "objective") {\n                        Ok(value) => value.to_owned(),\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.start(agent_id, objective).await {\n                        Ok(operation_id) => {\n                            ToolOutcome::text(format!("agent {agent_id} started: {operation_id}"))\n                        }\n                        Err(crate::agent::Error::UnknownAgent(_)) => ToolOutcome::error(\n                            "agent_start currently applies only to admitted lane agents; fresh/fork agents start at admission and use agent_resume after process loss",\n                        ),\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
new = '''                HostAgentToolKind::Start => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    let objective = match host_string_arg(&arguments, "objective") {\n                        Ok(value) => value.to_owned(),\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.target(agent_id).await {\n                        Ok(crate::agent::AgentTarget::SharedHistory { .. }) => {\n                            match self.family.start(agent_id, objective).await {\n                                Ok(operation_id) => ToolOutcome::text(format!(\n                                    "agent {agent_id} started: {operation_id}"\n                                )),\n                                Err(err) => ToolOutcome::error(err.to_string()),\n                            }\n                        }\n                        Ok(crate::agent::AgentTarget::SeparateSession { .. }) => ToolOutcome::error(\n                            "agent_start currently applies only to admitted lane agents; fresh/fork agents start at admission and use agent_resume after process loss",\n                        ),\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
if old not in text:
    raise SystemExit("host Start anchor missing")
text = text.replace(old, new, 1)
old = '''                HostAgentToolKind::Status => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.observe(agent_id).await {\n                        Ok(observation) => {\n                            ToolOutcome::text(render_family_observation(&observation))\n                        }\n                        Err(crate::agent::Error::UnknownAgent(_)) => {\n                            let handle = child_handle_for(agent_id, self.children.parent_id);\n                            match self.children.observe(handle).await {\n                                Ok(observation) => {\n                                    ToolOutcome::text(render_child_as_agent(agent_id, &observation))\n                                }\n                                Err(err) => ToolOutcome::error(err),\n                            }\n                        }\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
new = '''                HostAgentToolKind::Status => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.target(agent_id).await {\n                        Ok(crate::agent::AgentTarget::SharedHistory { .. }) => {\n                            match self.family.observe(agent_id).await {\n                                Ok(observation) => {\n                                    ToolOutcome::text(render_family_observation(&observation))\n                                }\n                                Err(err) => ToolOutcome::error(err.to_string()),\n                            }\n                        }\n                        Ok(crate::agent::AgentTarget::SeparateSession { session_id }) => {\n                            let handle = child_handle_for_session(session_id, self.children.parent_id);\n                            match self.children.observe(handle).await {\n                                Ok(observation) => {\n                                    ToolOutcome::text(render_child_as_agent(agent_id, &observation))\n                                }\n                                Err(err) => ToolOutcome::error(err),\n                            }\n                        }\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
if old not in text:
    raise SystemExit("host Status anchor missing")
text = text.replace(old, new, 1)
old = '''                HostAgentToolKind::Wait => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.wait_one(agent_id, cancel.clone(), None).await {\n                        Ok(status) => {\n                            let operation_id = host_status_operation_id(&status)\n                                .expect("family wait rejects admitted agents");\n                            match self.family.observe_operation(agent_id, operation_id).await {\n                                Ok(observation) => {\n                                    ToolOutcome::text(render_family_observation(&observation))\n                                }\n                                Err(err) => ToolOutcome::error(err.to_string()),\n                            }\n                        }\n                        Err(crate::agent::Error::UnknownAgent(_)) => {\n                            let handle = child_handle_for(agent_id, self.children.parent_id);\n                            match self.children.wait(handle, cancel, progress.as_ref()).await {\n                                Ok(observation) => {\n                                    ToolOutcome::text(render_child_as_agent(agent_id, &observation))\n                                }\n                                Err(err) => ToolOutcome::error(err),\n                            }\n                        }\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
new = '''                HostAgentToolKind::Wait => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.target(agent_id).await {\n                        Ok(crate::agent::AgentTarget::SharedHistory { .. }) => {\n                            let status = match self.family.wait_one(agent_id, cancel, None).await {\n                                Ok(status) => status,\n                                Err(err) => return ToolOutcome::error(err.to_string()),\n                            };\n                            let operation_id = host_status_operation_id(&status)\n                                .expect("family wait rejects admitted agents");\n                            match self.family.observe_operation(agent_id, operation_id).await {\n                                Ok(observation) => {\n                                    ToolOutcome::text(render_family_observation(&observation))\n                                }\n                                Err(err) => ToolOutcome::error(err.to_string()),\n                            }\n                        }\n                        Ok(crate::agent::AgentTarget::SeparateSession { session_id }) => {\n                            let handle = child_handle_for_session(session_id, self.children.parent_id);\n                            match self.children.wait(handle, cancel, progress.as_ref()).await {\n                                Ok(observation) => {\n                                    ToolOutcome::text(render_child_as_agent(agent_id, &observation))\n                                }\n                                Err(err) => ToolOutcome::error(err),\n                            }\n                        }\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
if old not in text:
    raise SystemExit("host Wait anchor missing")
text = text.replace(old, new, 1)
old = '''                HostAgentToolKind::Cancel => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.cancel(agent_id).await {\n                        Ok(()) => {\n                            ToolOutcome::text(format!("cancellation accepted for agent {agent_id}"))\n                        }\n                        Err(crate::agent::Error::UnknownAgent(_)) => {\n                            let handle = child_handle_for(agent_id, self.children.parent_id);\n                            match self.children.cancel(handle).await {\n                                Ok(()) => ToolOutcome::text(format!(\n                                    "cancellation accepted for agent {agent_id}"\n                                )),\n                                Err(err) => ToolOutcome::error(err),\n                            }\n                        }\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
new = '''                HostAgentToolKind::Cancel => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.target(agent_id).await {\n                        Ok(crate::agent::AgentTarget::SharedHistory { .. }) => {\n                            match self.family.cancel(agent_id).await {\n                                Ok(()) => ToolOutcome::text(format!(\n                                    "cancellation accepted for agent {agent_id}"\n                                )),\n                                Err(err) => ToolOutcome::error(err.to_string()),\n                            }\n                        }\n                        Ok(crate::agent::AgentTarget::SeparateSession { session_id }) => {\n                            let handle = child_handle_for_session(session_id, self.children.parent_id);\n                            match self.children.cancel(handle).await {\n                                Ok(()) => ToolOutcome::text(format!(\n                                    "cancellation accepted for agent {agent_id}"\n                                )),\n                                Err(err) => ToolOutcome::error(err),\n                            }\n                        }\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
if old not in text:
    raise SystemExit("host Cancel anchor missing")
text = text.replace(old, new, 1)
old = '''                HostAgentToolKind::Resume => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.status(agent_id).await {\n                        Ok(_) => ToolOutcome::error(\n                            "lane agents reattach with their root session and do not require agent_resume",\n                        ),\n                        Err(crate::agent::Error::UnknownAgent(_)) => {\n                            let handle = child_handle_for(agent_id, self.children.parent_id);\n                            match self\n                                .children\n                                .resume(handle, cancel, progress.as_ref())\n                                .await\n                            {\n                                Ok(observation) => {\n                                    ToolOutcome::text(render_child_as_agent(agent_id, &observation))\n                                }\n                                Err(err) => ToolOutcome::error(err),\n                            }\n                        }\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
new = '''                HostAgentToolKind::Resume => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.target(agent_id).await {\n                        Ok(crate::agent::AgentTarget::SharedHistory { .. }) => ToolOutcome::error(\n                            "lane agents reattach with their root session and do not require agent_resume",\n                        ),\n                        Ok(crate::agent::AgentTarget::SeparateSession { session_id }) => {\n                            let handle = child_handle_for_session(session_id, self.children.parent_id);\n                            match self\n                                .children\n                                .resume(handle, cancel, progress.as_ref())\n                                .await\n                            {\n                                Ok(observation) => {\n                                    ToolOutcome::text(render_child_as_agent(agent_id, &observation))\n                                }\n                                Err(err) => ToolOutcome::error(err),\n                            }\n                        }\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
if old not in text:
    raise SystemExit("host Resume anchor missing")
text = text.replace(old, new, 1)
old = '''                HostAgentToolKind::Send => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    let message = match host_string_arg(&arguments, "message") {\n                        Ok(value) => value.to_owned(),\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self\n                        .family\n                        .send(self.family.root(), agent_id, message)\n                        .await\n                    {\n                        Ok(operation_id) => ToolOutcome::text(format!(\n                            "message accepted for agent {agent_id}: {operation_id}"\n                        )),\n                        Err(crate::agent::Error::UnknownAgent(_)) => ToolOutcome::error(\n                            "agent_send for fresh/fork agents awaits cross-session durable input routing",\n                        ),\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
new = '''                HostAgentToolKind::Send => {\n                    let agent_id = match parse_host_agent_handle(&arguments) {\n                        Ok(agent_id) => agent_id,\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    let message = match host_string_arg(&arguments, "message") {\n                        Ok(value) => value.to_owned(),\n                        Err(err) => return ToolOutcome::error(err),\n                    };\n                    match self.family.target(agent_id).await {\n                        Ok(crate::agent::AgentTarget::SharedHistory { .. }) => match self\n                            .family\n                            .send(self.family.root(), agent_id, message)\n                            .await\n                        {\n                            Ok(operation_id) => ToolOutcome::text(format!(\n                                "message accepted for agent {agent_id}: {operation_id}"\n                            )),\n                            Err(err) => ToolOutcome::error(err.to_string()),\n                        },\n                        Ok(crate::agent::AgentTarget::SeparateSession { .. }) => ToolOutcome::error(\n                            "agent_send for fresh/fork agents awaits cross-session durable input routing",\n                        ),\n                        Err(err) => ToolOutcome::error(err.to_string()),\n                    }\n                }\n'''
if old not in text:
    raise SystemExit("host Send anchor missing")
text = text.replace(old, new, 1)
old = '''fn child_handle_for(agent_id: crate::ids::AgentId, parent_id: SessionId) -> ChildHandle {\n    ChildHandle {\n        session_id: SessionId::from_uuid(agent_id.as_uuid()),\n        control_parent_session_id: parent_id,\n    }\n}\n'''
new = '''fn child_handle_for_session(session_id: SessionId, parent_id: SessionId) -> ChildHandle {\n    ChildHandle {\n        session_id,\n        control_parent_session_id: parent_id,\n    }\n}\n'''
if old not in text:
    raise SystemExit("child_handle_for anchor missing")
text = text.replace(old, new, 1)
p.write_text(text)

# Tests: family discovery spans sessions dynamically, while LoadedSession stays
# session-local.
p = Path("crates/ion-core/src/tests/agent_store.rs")
text = p.read_text()
old = '''    let root = store.load(root_session).await.expect("root reload");\n    assert_eq!(root.agents.len(), 1);\n    assert!(matches!(\n        root.agents[0].history,\n        crate::store::AgentHistory::Root\n    ));\n\n    store.close().await.expect("close store");\n'''
new = '''    let root = store.load(root_session).await.expect("root reload");\n    assert_eq!(root.agents.len(), 1);\n    assert!(matches!(\n        root.agents[0].history,\n        crate::store::AgentHistory::Root\n    ));\n    let family = store\n        .load_agent_family(root_session)\n        .await\n        .expect("family topology");\n    assert_eq!(family.len(), 3);\n    assert!(family.iter().any(|agent| agent.id == root_agent));\n    assert!(family.iter().any(|agent| agent.id == fresh_agent));\n    assert!(family.iter().any(|agent| agent.id == fork_agent));\n\n    store.close().await.expect("close store");\n'''
if old not in text:
    raise SystemExit("agent_store family assertion anchor missing")
p.write_text(text.replace(old, new, 1))

p = Path("crates/ion-core/src/tests/agent_family.rs")
text = p.read_text()
old = '''    let lane_handle = handle_from(&lane.output);\n    let lane_wait = wait(lane_handle).await;\n'''
new = '''    let lane_handle = handle_from(&lane.output);\n    let lane_agent = crate::AgentId::parse(\n        lane_handle\n            .strip_prefix("agent-")\n            .expect("lane agent prefix"),\n    )\n    .expect("lane agent id");\n    assert_eq!(\n        family.target(lane_agent).await.expect("lane target"),\n        crate::agent::AgentTarget::SharedHistory {\n            session_id: runtime.session_id(),\n        }\n    );\n    let lane_wait = wait(lane_handle).await;\n'''
if old not in text:
    raise SystemExit("lane target test anchor missing")
text = text.replace(old, new, 1)
old = '''    let fresh_loaded = store.load(fresh_session).await.expect("fresh session");\n    assert_eq!(\n        fresh_loaded.session.control_parent_session_id,\n'''
new = '''    assert_eq!(\n        family.target(fresh_agent).await.expect("fresh target"),\n        crate::agent::AgentTarget::SeparateSession {\n            session_id: fresh_session,\n        }\n    );\n    let fresh_loaded = store.load(fresh_session).await.expect("fresh session");\n    assert_eq!(\n        fresh_loaded.session.control_parent_session_id,\n'''
if old not in text:
    raise SystemExit("fresh target test anchor missing")
text = text.replace(old, new, 1)
old = '''    let fork_loaded = store.load(fork_session).await.expect("fork session");\n    assert_eq!(\n        fork_loaded.session.control_parent_session_id,\n'''
new = '''    assert_eq!(\n        family.target(fork_agent).await.expect("fork target"),\n        crate::agent::AgentTarget::SeparateSession {\n            session_id: fork_session,\n        }\n    );\n    let fork_loaded = store.load(fork_session).await.expect("fork session");\n    assert_eq!(\n        fork_loaded.session.control_parent_session_id,\n'''
if old not in text:
    raise SystemExit("fork target test anchor missing")
p.write_text(text.replace(old, new, 1))
