from pathlib import Path

p = Path("crates/ion-core/src/delegate.rs")
text = p.read_text()
old = '''        let catalog = crate::tool::ToolCatalog::read_only(&self.config.cwd);\n        let runtime = Runtime::start_child_with_resources(\n            provider,\n            catalog.clone(),\n            self.config.store.clone(),\n            Arc::new(crate::policy::DefaultPolicy),\n            self.config.child_budget,\n            crate::runtime::ChildSessionLineage {\n                control_parent: self.parent_id,\n                fork_source: fork_source.map(|(session_id, entry_id)| {\n                    crate::runtime::SessionForkSource {\n                        session_id,\n                        entry_id,\n                    }\n                }),\n            },\n            self.config.trusted_resources.clone(),\n        );\n        let session_id = runtime.session_id();\n        let session = runtime.session();\n        let operation_id = match session.submit_if_idle(prompt).await {\n            Ok(operation_id) => operation_id,\n            Err(err) => {\n                let _ = session.close().await;\n                let _ = runtime.join().await;\n                let _ = catalog.close().await;\n                return Err(format!("child submit failed: {err}"));\n            }\n        };\n'''
new = '''        let catalog = crate::tool::ToolCatalog::read_only(&self.config.cwd);\n        let session_id = SessionId::generate();\n        let agent_id = crate::ids::AgentId::root(session_id);\n        let initial_model_ref = provider.initial_model_ref();\n        self.config\n            .store\n            .admit_session_agent(\n                crate::store::SessionRecord {\n                    id: session_id,\n                    cwd: self.config.cwd.to_string_lossy().into_owned(),\n                    title: String::new(),\n                    initial_model_ref,\n                    control_parent_session_id: Some(self.parent_id),\n                    fork_source_session_id: fork_source.map(|(session_id, _)| session_id),\n                    fork_source_entry_id: fork_source.and_then(|(_, entry_id)| entry_id),\n                },\n                crate::ids::AgentId::root(self.parent_id),\n            )\n            .await\n            .map_err(|err| format!("child agent admission failed: {err}"))?;\n        let runtime = match Runtime::open_child(\n            provider,\n            catalog.clone(),\n            self.config.store.clone(),\n            session_id,\n            crate::runtime::ChildRuntimeConfig {\n                policy: Arc::new(crate::policy::DefaultPolicy),\n                budget: self.config.child_budget,\n                control_parent: self.parent_id,\n                trusted_resources: self.config.trusted_resources.clone(),\n            },\n        )\n        .await\n        {\n            Ok(runtime) => runtime,\n            Err(err) => {\n                let _ = catalog.close().await;\n                return Err(format!(\n                    "child agent {agent_id} was admitted, but runtime open failed: {err}"\n                ));\n            }\n        };\n        let session = runtime.session();\n        let operation_id = match session.submit_if_idle(prompt).await {\n            Ok(operation_id) => operation_id,\n            Err(err) => {\n                let _ = session.close().await;\n                let _ = runtime.join().await;\n                let _ = catalog.close().await;\n                return Err(format!(\n                    "child agent {agent_id} was admitted, but start failed: {err}"\n                ));\n            }\n        };\n'''
if old not in text:
    raise SystemExit("ChildManager spawn runtime-construction anchor missing")
p.write_text(text.replace(old, new, 1))

# Assert the production unified fresh/fork path uses the new family-scoped
# durable identity. The legacy `delegate` helper intentionally remains a
# separate migration surface for now.
p = Path("crates/ion-core/src/tests/agent_family.rs")
text = p.read_text()
old = '''    assert_eq!(fresh_loaded.session.fork_source_session_id, None);\n    let fresh_wait = wait(fresh_handle).await;\n'''
new = '''    assert_eq!(fresh_loaded.session.fork_source_session_id, None);\n    assert_eq!(fresh_loaded.agents.len(), 1);\n    assert_eq!(fresh_loaded.agents[0].id, fresh_agent);\n    assert_eq!(fresh_loaded.agents[0].family_session_id, runtime.session_id());\n    assert_eq!(\n        fresh_loaded.agents[0].control_parent_id,\n        Some(crate::AgentId::root(runtime.session_id()))\n    );\n    assert!(matches!(\n        fresh_loaded.agents[0].history,\n        crate::store::AgentHistory::Fresh\n    ));\n    let fresh_wait = wait(fresh_handle).await;\n'''
if old not in text:
    raise SystemExit("unified fresh topology anchor missing")
text = text.replace(old, new, 1)
old = '''    assert_eq!(\n        fork_loaded.session.fork_source_session_id,\n        Some(runtime.session_id())\n    );\n    let fork_wait = wait(fork_handle).await;\n'''
new = '''    assert_eq!(\n        fork_loaded.session.fork_source_session_id,\n        Some(runtime.session_id())\n    );\n    let fork_source_entry = fork_loaded\n        .session\n        .fork_source_entry_id\n        .expect("fork source entry");\n    assert_eq!(fork_loaded.agents.len(), 1);\n    assert_eq!(fork_loaded.agents[0].id, fork_agent);\n    assert_eq!(fork_loaded.agents[0].family_session_id, runtime.session_id());\n    assert_eq!(\n        fork_loaded.agents[0].control_parent_id,\n        Some(crate::AgentId::root(runtime.session_id()))\n    );\n    assert!(matches!(\n        fork_loaded.agents[0].history,\n        crate::store::AgentHistory::Fork {\n            source_session_id,\n            source_entry_id: Some(entry_id),\n        } if source_session_id == runtime.session_id() && entry_id == fork_source_entry\n    ));\n    let fork_wait = wait(fork_handle).await;\n'''
if old not in text:
    raise SystemExit("unified fork topology anchor missing")
p.write_text(text.replace(old, new, 1))
