from pathlib import Path

p = Path("crates/ion-core/src/delegate.rs")
text = p.read_text()
old = '''        let catalog = crate::tool::ToolCatalog::read_only(&self.config.cwd);\n        let runtime = Runtime::start_child_with_resources(\n            provider,\n            catalog.clone(),\n            self.config.store.clone(),\n            Arc::new(crate::policy::DefaultPolicy),\n            self.config.child_budget,\n            crate::runtime::ChildSessionLineage {\n                control_parent: self.parent_id,\n                fork_source: fork_source.map(|(session_id, entry_id)| {\n                    crate::runtime::SessionForkSource {\n                        session_id,\n                        entry_id,\n                    }\n                }),\n            },\n            self.config.trusted_resources.clone(),\n        );\n        let session_id = runtime.session_id();\n        let session = runtime.session();\n        let operation_id = match session.submit_if_idle(prompt).await {\n            Ok(operation_id) => operation_id,\n            Err(err) => {\n                let _ = session.close().await;\n                let _ = runtime.join().await;\n                let _ = catalog.close().await;\n                return Err(format!("child submit failed: {err}"));\n            }\n        };\n'''
new = '''        let catalog = crate::tool::ToolCatalog::read_only(&self.config.cwd);\n        let session_id = SessionId::generate();\n        let agent_id = crate::ids::AgentId::root(session_id);\n        let initial_model_ref = provider.initial_model_ref();\n        self.config\n            .store\n            .admit_session_agent(\n                crate::store::SessionRecord {\n                    id: session_id,\n                    cwd: self.config.cwd.to_string_lossy().into_owned(),\n                    title: String::new(),\n                    initial_model_ref,\n                    control_parent_session_id: Some(self.parent_id),\n                    fork_source_session_id: fork_source.map(|(session_id, _)| session_id),\n                    fork_source_entry_id: fork_source.and_then(|(_, entry_id)| entry_id),\n                },\n                crate::ids::AgentId::root(self.parent_id),\n            )\n            .await\n            .map_err(|err| format!("child agent admission failed: {err}"))?;\n        let runtime = match Runtime::open_child(\n            provider,\n            catalog.clone(),\n            self.config.store.clone(),\n            session_id,\n            crate::runtime::ChildRuntimeConfig {\n                policy: Arc::new(crate::policy::DefaultPolicy),\n                budget: self.config.child_budget,\n                control_parent: self.parent_id,\n                trusted_resources: self.config.trusted_resources.clone(),\n            },\n        )\n        .await\n        {\n            Ok(runtime) => runtime,\n            Err(err) => {\n                let _ = catalog.close().await;\n                return Err(format!(\n                    "child agent {agent_id} was admitted, but runtime open failed: {err}"\n                ));\n            }\n        };\n        let session = runtime.session();\n        let operation_id = match session.submit_if_idle(prompt).await {\n            Ok(operation_id) => operation_id,\n            Err(err) => {\n                let _ = session.close().await;\n                let _ = runtime.join().await;\n                let _ = catalog.close().await;\n                return Err(format!(\n                    "child agent {agent_id} was admitted, but start failed: {err}"\n                ));\n            }\n        };\n'''
if old not in text:
    raise SystemExit("ChildManager spawn runtime-construction anchor missing")
p.write_text(text.replace(old, new, 1))

# The session-agent transaction must now have a production owner, not only
# store tests. Assert both fresh and fork child backends load with the family
# topology that ChildManager just admitted.
p = Path("crates/ion-core/src/tests/budget_children.rs")
text = p.read_text()
old = '''    let child = store.load(child_id).await.expect("child session");\n    assert_eq!(child.session.initial_model_ref, "child-model");\n'''
new = '''    let child = store.load(child_id).await.expect("child session");\n    assert_eq!(child.session.initial_model_ref, "child-model");\n    assert_eq!(child.agents.len(), 1);\n    assert_eq!(child.agents[0].id, crate::AgentId::root(child_id));\n    assert_eq!(child.agents[0].family_session_id, parent_id);\n    assert_eq!(\n        child.agents[0].control_parent_id,\n        Some(crate::AgentId::root(parent_id))\n    );\n    assert!(matches!(\n        child.agents[0].history,\n        crate::store::AgentHistory::Fork {\n            source_session_id,\n            source_entry_id: Some(_),\n        } if source_session_id == parent_id\n    ));\n'''
if old not in text:
    raise SystemExit("fork child topology assertion anchor missing")
p.write_text(text.replace(old, new, 1))
