[workspace]
resolver = "3"
members = ["crates/ion", "crates/ion-core", "crates/ion-terminal"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.94.0"
license = "MIT"
repository = "https://github.com/nijaru/ion"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.dependencies]
clap = { version = "4.6.6", features = ["derive"] }
ion-core = { path = "crates/ion-core" }
ion-terminal = { path = "crates/ion-terminal" }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.19", features = ["rt"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
