package export

import (
	"strings"
	"testing"
	"time"

	"github.com/nijaru/ion/llm"
	"github.com/nijaru/ion/session"
)

func TestGenerateHTMLContainsEntries(t *testing.T) {
	data := SessionData{
		SessionID: "test-session-12345678",
		Entries: []session.HistoryEntry{
			{Message: llm.Message{Role: llm.RoleUser, Content: "Hello"}},
			{Message: llm.Message{Role: llm.RoleAssistant, Content: "Hi there!"}},
			{Message: llm.Message{Role: llm.RoleTool, Name: "bash", Content: "ls -la"}},
		},
		Exported: time.Date(2026, 6, 22, 12, 0, 0, 0, time.UTC),
	}

	html := GenerateHTML(data)

	checks := []struct {
		name, want string
	}{
		{"doctype", "<!DOCTYPE html>"},
		{"title", "Ion Session"},
		{"session ID", "test-ses"},
		{"user role", "You"},
		{"user content", "Hello"},
		{"assistant role", "Assistant"},
		{"assistant content", "Hi there!"},
		{"tool role", "bash"},
		{"tool content", "ls -la"},
		{"footer", "Generated by Ion"},
		{"closing html", "</html>"},
	}
	for _, c := range checks {
		if !strings.Contains(html, c.want) {
			t.Errorf("%s: missing %q in output", c.name, c.want)
		}
	}
}

func TestGenerateHTMLEmptyReasoningOmitted(t *testing.T) {
	data := SessionData{
		SessionID: "test",
		Entries: []session.HistoryEntry{
			{Message: llm.Message{Role: llm.RoleAssistant, Content: "answer", Reasoning: ""}},
		},
		Exported: time.Now(),
	}

	html := GenerateHTML(data)
	if strings.Contains(html, "Thinking") {
		t.Error("empty reasoning should not produce Thinking section")
	}
}

func TestGenerateHTMLReasoningIncluded(t *testing.T) {
	data := SessionData{
		SessionID: "test",
		Entries: []session.HistoryEntry{
			{Message: llm.Message{Role: llm.RoleAssistant, Content: "answer", Reasoning: "let me think..."}},
		},
		Exported: time.Now(),
	}

	html := GenerateHTML(data)
	if !strings.Contains(html, "Thinking") {
		t.Error("non-empty reasoning should produce Thinking section")
	}
	if !strings.Contains(html, "let me think...") {
		t.Error("reasoning content should appear in HTML")
	}
}

func TestGenerateHTMLEscapesContent(t *testing.T) {
	data := SessionData{
		SessionID: "test",
		Entries: []session.HistoryEntry{
			{Message: llm.Message{Role: llm.RoleUser, Content: "<script>alert('xss')</script>"}},
		},
		Exported: time.Now(),
	}

	html := GenerateHTML(data)
	if strings.Contains(html, "<script>") {
		t.Error("HTML content should be escaped")
	}
	if !strings.Contains(html, "&lt;script&gt;") {
		t.Error("escaped tags should appear")
	}
}

func TestGenerateHTMLSkipsEmptyEntries(t *testing.T) {
	data := SessionData{
		SessionID: "test",
		Entries: []session.HistoryEntry{
			{Message: llm.Message{Role: llm.RoleUser, Content: "hello"}},
			{Message: llm.Message{Role: llm.RoleAssistant, Content: ""}},
			{Message: llm.Message{Role: llm.RoleUser, Content: "bye"}},
		},
		Exported: time.Now(),
	}

	html := GenerateHTML(data)
	if strings.Count(html, "class=\"entry") != 2 {
		t.Errorf("expected 2 entries, got %d", strings.Count(html, "class=\"entry"))
	}
}
