package export

import (
	"strings"
	"testing"
	"time"

	"github.com/nijaru/ion/session"
)

func TestGenerateHTMLContainsEntries(t *testing.T) {
	userMsg := &session.UserMessage{
		Content:   []session.Content{session.TextContent{Text: "Hello"}},
		Timestamp: time.Date(2026, 6, 22, 12, 0, 0, 0, time.UTC),
	}
	assistantMsg := &session.AssistantMessage{
		Content: []session.Content{session.TextContent{Text: "Hi there!"}},
	}
	toolMsg := &session.ToolResultMessage{
		ToolCallID: "tool-1",
		ToolName:   "bash",
		Content:    []session.Content{session.TextContent{Text: "ls -la"}},
	}

	data := SessionData{
		SessionID: "test-session-12345678",
		Entries: []session.Entry{
			&session.MessageEntry{Message: userMsg},
			&session.MessageEntry{Message: assistantMsg},
			&session.MessageEntry{Message: toolMsg},
		},
		Exported: time.Date(2026, 6, 22, 12, 0, 0, 0, time.UTC),
	}

	html := GenerateHTML(data)

	checks := []struct {
		name, want string
	}{
		{"doctype", "<!DOCTYPE html>"},
		{"title", "Ion Session"},
		{"session ID", "test-ses"},
		{"user role", "You"},
		{"user content", "Hello"},
		{"assistant role", "Assistant"},
		{"assistant content", "Hi there!"},
		{"tool role", "bash"},
		{"tool content", "ls -la"},
		{"footer", "Generated by Ion"},
		{"closing html", "</html>"},
	}
	for _, c := range checks {
		if !strings.Contains(html, c.want) {
			t.Errorf("%s: expected %q in HTML", c.name, c.want)
		}
	}
}

func TestEntryToHTMLSkipsNonMessageEntries(t *testing.T) {
	// Non-message entries should produce empty string.
	entry := &session.LabelEntry{}
	html := EntryToHTML(entry)
	if html != "" {
		t.Errorf("expected empty HTML for non-message entry, got %q", html)
	}
}
