package llm

import (
	"context"
	"sync"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

const meterName = "github.com/nijaru/canto/llm"

var (
	usageMetricsOnce sync.Once
	usageMetricsOK   bool

	inputTokensCounter         metric.Int64Counter
	outputTokensCounter        metric.Int64Counter
	cacheReadTokensCounter     metric.Int64Counter
	cacheCreationTokensCounter metric.Int64Counter
	totalTokensCounter         metric.Int64Counter
	costCounter                metric.Float64Counter

	inputTokensHistogram         metric.Int64Histogram
	outputTokensHistogram        metric.Int64Histogram
	cacheReadTokensHistogram     metric.Int64Histogram
	cacheCreationTokensHistogram metric.Int64Histogram
	totalTokensHistogram         metric.Int64Histogram
	costHistogram                metric.Float64Histogram
)

func ensureUsageMetrics() bool {
	usageMetricsOnce.Do(func() {
		meter := otel.Meter(meterName)
		var err error

		inputTokensCounter, err = meter.Int64Counter(
			"gen_ai.usage.input_tokens",
			metric.WithDescription("Number of input tokens consumed by LLM calls"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		outputTokensCounter, err = meter.Int64Counter(
			"gen_ai.usage.output_tokens",
			metric.WithDescription("Number of output tokens generated by LLM calls"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		cacheReadTokensCounter, err = meter.Int64Counter(
			"gen_ai.usage.cache_read.input_tokens",
			metric.WithDescription("Number of input tokens read from cache"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		cacheCreationTokensCounter, err = meter.Int64Counter(
			"gen_ai.usage.cache_creation.input_tokens",
			metric.WithDescription("Number of input tokens written to cache"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		totalTokensCounter, err = meter.Int64Counter(
			"gen_ai.usage.total_tokens",
			metric.WithDescription("Total tokens consumed by LLM calls"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		costCounter, err = meter.Float64Counter(
			"gen_ai.usage.cost",
			metric.WithDescription("Estimated cost of LLM calls in USD"),
			metric.WithUnit("USD"),
		)
		if err != nil {
			return
		}

		inputTokensHistogram, err = meter.Int64Histogram(
			"gen_ai.usage.input_tokens.per_call",
			metric.WithDescription("Per-call input token usage"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		outputTokensHistogram, err = meter.Int64Histogram(
			"gen_ai.usage.output_tokens.per_call",
			metric.WithDescription("Per-call output token usage"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		cacheReadTokensHistogram, err = meter.Int64Histogram(
			"gen_ai.usage.cache_read.input_tokens.per_call",
			metric.WithDescription("Per-call cache-read token usage"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		cacheCreationTokensHistogram, err = meter.Int64Histogram(
			"gen_ai.usage.cache_creation.input_tokens.per_call",
			metric.WithDescription("Per-call cache-creation token usage"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		totalTokensHistogram, err = meter.Int64Histogram(
			"gen_ai.usage.total_tokens.per_call",
			metric.WithDescription("Per-call total token usage"),
			metric.WithUnit("{token}"),
		)
		if err != nil {
			return
		}

		costHistogram, err = meter.Float64Histogram(
			"gen_ai.usage.cost.per_call",
			metric.WithDescription("Per-call estimated LLM cost in USD"),
			metric.WithUnit("USD"),
		)
		if err != nil {
			return
		}

		usageMetricsOK = true
	})

	return usageMetricsOK
}

// RecordUsage emits OpenTelemetry metrics for a completed LLM call.
func RecordUsage(ctx context.Context, providerID, modelID string, usage Usage) {
	if !ensureUsageMetrics() {
		return
	}

	totalTokens := usage.TotalTokens
	if totalTokens == 0 {
		totalTokens = usage.InputTokens + usage.OutputTokens
	}

	attrsList := []attribute.KeyValue{attribute.String("gen_ai.request.model", modelID)}
	if providerID != "" {
		attrsList = append(attrsList, attribute.String("canto.provider_id", providerID))
	}
	attrs := metric.WithAttributes(attrsList...)

	inputTokensCounter.Add(ctx, int64(usage.InputTokens), attrs)
	outputTokensCounter.Add(ctx, int64(usage.OutputTokens), attrs)
	cacheReadTokensCounter.Add(ctx, int64(usage.CacheReadTokens), attrs)
	cacheCreationTokensCounter.Add(ctx, int64(usage.CacheCreationTokens), attrs)
	totalTokensCounter.Add(ctx, int64(totalTokens), attrs)
	costCounter.Add(ctx, usage.Cost, attrs)

	inputTokensHistogram.Record(ctx, int64(usage.InputTokens), attrs)
	outputTokensHistogram.Record(ctx, int64(usage.OutputTokens), attrs)
	cacheReadTokensHistogram.Record(ctx, int64(usage.CacheReadTokens), attrs)
	cacheCreationTokensHistogram.Record(ctx, int64(usage.CacheCreationTokens), attrs)
	totalTokensHistogram.Record(ctx, int64(totalTokens), attrs)
	costHistogram.Record(ctx, usage.Cost, attrs)
}
